### ISSUE TITLE
crash when i cheat

### ISSUE THREAD

**Issue by Oppossome** [xezno/sbox-instagib#6]
please it no work screen go black and game close

**Comment by liquiad** [comment]
this happe nto me too, and alex dont even merge my super awesome [pull request](https://github.com/xezno/sbox-instagib/pull/5)...... SMH....

**Comment by xezno** [comment]
H

**Comment by Oppossome** [comment]
h

**Comment by xezno** [comment]
> h

Agreed

**Comment by Oppossome** [comment]
wetf!

**Comment by xezno** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed.

If it is fixed feel free to close the issue yourself <3
